import type { Service } from "./types";

export const services: Service[] = [
  {
    id: "infinitepay",
    name: "InfinitePay",
    description: "Integração de pagamentos — checkouts, webhooks, relatórios AI",
    status: "healthy",
    category: "payment",
    host: "10.10.10.120",
    port: 80,
    baseUrl: "http://10.10.10.120",
    openApiUrl: "http://10.10.10.120/openapi.json",
    uptime: "32d 4h 12m",
    cpu: 42,
    memory: 68,
    latency: 4,
    requestsPerSecond: 2847,
    version: "1.0.0",
    dependencies: [],
    tags: ["payments", "stripe", "checkout", "ai", "webhook"],
  },
  {
    id: "webhook-capture",
    name: "Webhook Capture",
    description: "Captura, inspeção, AI analyze e replay de webhooks HTTP",
    status: "healthy",
    category: "integration",
    host: "10.10.10.129",
    port: 80,
    baseUrl: "http://10.10.10.129",
    uptime: "30d 7h 12m",
    cpu: 5,
    memory: 25,
    latency: 8,
    requestsPerSecond: 45,
    version: "1.0.0",
    dependencies: [],
    tags: ["webhook", "capture", "debug", "inspect", "ai"],
  },
  {
    id: "api-gateway",
    name: "API Gateway",
    description: "Roteamento, rate limiting e autenticação centralizada",
    status: "healthy",
    category: "gateway",
    host: "10.10.10.120",
    port: 443,
    baseUrl: "https://10.10.10.120",
    uptime: "32d 4h 12m",
    cpu: 42,
    memory: 68,
    latency: 4,
    requestsPerSecond: 2847,
    version: "3.2.1",
    dependencies: ["auth", "users", "payments"],
    tags: ["nginx", "kong", "tls", "proxy"],
  },
  {
    id: "auth",
    name: "Auth Service",
    description: "Autenticação JWT, OAuth2, RBAC e SSO",
    status: "healthy",
    category: "core",
    host: "10.10.10.121",
    port: 3001,
    baseUrl: "https://10.10.10.121",
    uptime: "60d 1h 45m",
    cpu: 18,
    memory: 42,
    latency: 7,
    requestsPerSecond: 1200,
    version: "2.5.0",
    dependencies: ["postgres", "redis"],
    tags: ["jwt", "oauth2", "rbac", "sso"],
  },
  {
    id: "users",
    name: "User Service",
    description: "CRUD de usuários, perfis, permissões",
    status: "degraded",
    category: "core",
    host: "10.10.10.121",
    port: 3002,
    baseUrl: "https://10.10.10.121",
    uptime: "40d 12h 33m",
    cpu: 76,
    memory: 85,
    latency: 320,
    requestsPerSecond: 450,
    version: "1.10.2",
    dependencies: ["postgres", "redis", "auth"],
    tags: ["crud", "profiles", "permissions"],
  },
  {
    id: "payments",
    name: "Payment Service",
    description: "Processamento de pagamentos, faturas, billing engine",
    status: "healthy",
    category: "payment",
    host: "10.10.10.132",
    port: 3003,
    baseUrl: "https://10.10.10.132",
    uptime: "15d 7h 22m",
    cpu: 35,
    memory: 58,
    latency: 42,
    requestsPerSecond: 210,
    version: "4.3.1",
    dependencies: ["postgres", "redis", "auth"],
    tags: ["stripe", "billing", "invoices"],
  },
  {
    id: "notifications",
    name: "Notifications",
    description: "Email, SMS, push e WhatsApp",
    status: "healthy",
    category: "core",
    host: "10.10.10.132",
    port: 3004,
    baseUrl: "https://10.10.10.132",
    uptime: "28d 3h 15m",
    cpu: 14,
    memory: 32,
    latency: 180,
    requestsPerSecond: 890,
    version: "2.1.0",
    dependencies: ["redis", "rabbitmq"],
    tags: ["email", "sms", "push", "whatsapp"],
  },
  {
    id: "catalog",
    name: "Catalog Service",
    description: "Catálogo de produtos com busca full-text Elasticsearch",
    status: "down",
    category: "core",
    host: "10.10.10.132",
    port: 3005,
    baseUrl: "https://10.10.10.132",
    uptime: "0d 0h 0m",
    cpu: 0,
    memory: 0,
    latency: 0,
    requestsPerSecond: 0,
    version: "3.0.0",
    dependencies: ["elasticsearch", "postgres"],
    tags: ["search", "products", "elasticsearch"],
  },
  {
    id: "analytics",
    name: "Analytics",
    description: "Métricas de negócio, BI, relatórios e dashboards",
    status: "maintenance",
    category: "core",
    host: "10.10.10.132",
    port: 3006,
    baseUrl: "https://10.10.10.132",
    uptime: "5d 3h 0m",
    cpu: 8,
    memory: 22,
    latency: 0,
    requestsPerSecond: 0,
    version: "1.6.1",
    dependencies: ["postgres", "redis", "clickhouse"],
    tags: ["metrics", "bi", "reports"],
  },
  {
    id: "files",
    name: "File Storage",
    description: "Upload/download de arquivos, S3-compatible (MinIO)",
    status: "healthy",
    category: "storage",
    host: "10.10.10.127",
    port: 3007,
    baseUrl: "https://10.10.10.127",
    uptime: "62d 1h 5m",
    cpu: 25,
    memory: 38,
    latency: 60,
    requestsPerSecond: 180,
    version: "2.2.0",
    dependencies: ["minio"],
    tags: ["s3", "upload", "cdn", "storage"],
  },
  {
    id: "postgres",
    name: "PostgreSQL",
    description: "Banco relacional primário — dados transacionais",
    status: "healthy",
    category: "database",
    host: "10.10.10.133",
    port: 5432,
    baseUrl: "postgresql://10.10.10.133",
    uptime: "90d 10h 22m",
    cpu: 30,
    memory: 78,
    latency: 1,
    requestsPerSecond: 3200,
    version: "16.4",
    dependencies: [],
    tags: ["sql", "acid", "transactions", "replication"],
  },
  {
    id: "redis",
    name: "Redis",
    description: "Cache distribuído, filas, pub/sub, rate limiting",
    status: "healthy",
    category: "database",
    host: "10.10.10.133",
    port: 6379,
    baseUrl: "redis://10.10.10.133",
    uptime: "90d 10h 30m",
    cpu: 8,
    memory: 45,
    latency: 0,
    requestsPerSecond: 15000,
    version: "7.4.1",
    dependencies: [],
    tags: ["cache", "pubsub", "queue", "ratelimit"],
  },
  {
    id: "elasticsearch",
    name: "Elasticsearch",
    description: "Motor de busca full-text e analytics",
    status: "degraded",
    category: "database",
    host: "10.10.10.133",
    port: 9200,
    baseUrl: "https://10.10.10.133:9200",
    uptime: "45d 2h 15m",
    cpu: 55,
    memory: 92,
    latency: 250,
    requestsPerSecond: 600,
    version: "8.15.2",
    dependencies: [],
    tags: ["search", "fulltext", "elk"],
  },
  {
    id: "rabbitmq",
    name: "RabbitMQ",
    description: "Message broker — filas, exchanges, dead letters",
    status: "healthy",
    category: "messaging",
    host: "10.10.10.137",
    port: 5672,
    baseUrl: "amqp://10.10.10.137",
    uptime: "90d 10h 0m",
    cpu: 10,
    memory: 35,
    latency: 0,
    requestsPerSecond: 5000,
    version: "3.13.7",
    dependencies: [],
    tags: ["amqp", "queues", "pubsub", "dlq"],
  },
  {
    id: "nats",
    name: "NATS",
    description: "Cloud-native messaging — JetStream, key-value store",
    status: "healthy",
    category: "messaging",
    host: "10.10.10.137",
    port: 4222,
    baseUrl: "nats://10.10.10.137",
    uptime: "45d 3h 20m",
    cpu: 5,
    memory: 20,
    latency: 0,
    requestsPerSecond: 20000,
    version: "2.10.18",
    dependencies: [],
    tags: ["jetstream", "kv", "pubsub", "micro"],
  },
  {
    id: "prometheus",
    name: "Prometheus",
    description: "Coleta e armazenamento de métricas time-series",
    status: "healthy",
    category: "monitoring",
    host: "10.10.10.137",
    port: 9090,
    baseUrl: "https://10.10.10.137:9090",
    uptime: "60d 5h 30m",
    cpu: 12,
    memory: 48,
    latency: 15,
    requestsPerSecond: 200,
    version: "2.55.0",
    dependencies: [],
    tags: ["metrics", "tsdb", "alerting", "grafana"],
  },
  {
    id: "grafana",
    name: "Grafana",
    description: "Visualização de métricas, dashboards e alertas",
    status: "healthy",
    category: "monitoring",
    host: "10.10.10.137",
    port: 3000,
    baseUrl: "https://10.10.10.137:3000",
    uptime: "60d 5h 32m",
    cpu: 10,
    memory: 35,
    latency: 20,
    requestsPerSecond: 50,
    version: "11.3.0",
    dependencies: ["prometheus"],
    tags: ["dashboards", "visualization", "alerts"],
  },
  {
    id: "deepseek-proxy",
    name: "DeepSeek Proxy",
    description: "Proxy Anthropic-compatible para DeepSeek AI API",
    status: "healthy",
    category: "ai",
    host: "api.deepseek.com",
    port: 443,
    baseUrl: "https://api.deepseek.com/anthropic",
    uptime: "N/A",
    cpu: 0,
    memory: 0,
    latency: 450,
    requestsPerSecond: 10,
    version: "v4-pro",
    dependencies: [],
    tags: ["ai", "llm", "anthropic", "deepseek"],
  },
  {
    id: "proxmox",
    name: "Proxmox VE",
    description: "Hypervisor — containers LXC e VMs KVM/QEMU",
    status: "healthy",
    category: "other",
    host: "10.10.10.1",
    port: 8006,
    baseUrl: "https://10.10.10.1:8006",
    uptime: "120d 10h 45m",
    cpu: 25,
    memory: 60,
    latency: 2,
    requestsPerSecond: 0,
    version: "8.3",
    dependencies: [],
    tags: ["hypervisor", "lxc", "kvm", "containers"],
  },
  {
    id: "staff",
    name: "Staff Dashboard",
    description: "Container de admin — Boos Dashboard, Claude Code",
    status: "healthy",
    category: "other",
    host: "10.10.10.143",
    port: 3000,
    baseUrl: "http://10.10.10.143:3000",
    uptime: "5d 12h 30m",
    cpu: 15,
    memory: 35,
    latency: 1,
    requestsPerSecond: 5,
    version: "0.1.0",
    dependencies: ["deepseek-proxy", "webhook-capture"],
    tags: ["admin", "dashboard", "claude", "staff"],
  },
];

export function getServiceById(id: string): Service | undefined {
  return services.find((s) => s.id === id);
}

export function getServicesByCategory(): Record<string, Service[]> {
  return services.reduce(
    (acc, s) => {
      const cat = s.category || "other";
      if (!acc[cat]) acc[cat] = [];
      acc[cat].push(s);
      return acc;
    },
    {} as Record<string, Service[]>
  );
}

export function getServicesByStatus(): Record<string, Service[]> {
  return services.reduce(
    (acc, s) => {
      if (!acc[s.status]) acc[s.status] = [];
      acc[s.status].push(s);
      return acc;
    },
    {} as Record<string, Service[]>
  );
}
